### ISSUE TITLE
rule consistent-output crashing when invalid tests array has missing element.

### ISSUE THREAD

**Issue by Aladdin-ADD** [not-an-aardvark/eslint-plugin-eslint-plugin#37]
test case:
```js
// invalid
invalid: [
  {code:"foo"},
  ,
  {code: "bar"}
]
```

error:
```bash
TypeError: Cannot read property 'type' of null
    at testRun.invalid.filter.testCase (C:\repo\eslint\node_modules\eslint-plugin-eslint-plugin\lib\rules\consistent-output.js:36:7
6)
    at Array.filter (native)
    at Program.utils.getTestInfo.forEach.testRun (C:\repo\eslint\node_modules\eslint-plugin-eslint-plugin\lib\rules\consistent-outp
ut.js:36:49)
    at Array.forEach (native)
    at EventEmitter.Program (C:\repo\eslint\node_modules\eslint-plugin-eslint-plugin\lib\rules\consistent-output.js:32:41)
    at emitOne (events.js:120:20)
    at EventEmitter.emit (events.js:210:7)
    at NodeEventGenerator.applySelector (C:\repo\eslint\lib\util\node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (C:\repo\eslint\lib\util\node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (C:\repo\eslint\lib\util\node-event-generator.js:308:14)
```

**Comment by Aladdin-ADD** [comment]
similar to #35

**Comment by not-an-aardvark** [comment]
I wonder if it would be better to filter out missing elements in `utils.getTestInfo`. I can't imagine that rules would ever care about missing elements, and this would prevent rules from always having to do a null check.
